# API Client Base Class
# Day 033: API Clients
# Generated by AI Agent

import requests
from typing import Any, Dict, Optional

class APIClient:
    def __init__(self, base_url: str, headers: Optional[Dict] = None):
        self.base_url = base_url.rstrip('/')
        self.session = requests.Session()
        self.session.headers.update(headers or {})
    
    def get(self, endpoint: str) -> Any:
        url = f'{self.base_url}/{endpoint.lstrip("/")}'
        return self.session.get(url).json()
    
    def post(self, endpoint: str, data: Dict = None) -> Any:
        url = f'{self.base_url}/{endpoint.lstrip("/")}'
        return self.session.post(url, json=data).json()

if __name__ == '__main__':
    print('APIClient defined')
