#!/usr/bin/env python3
"""
Emoji Tools - Emoji Parser & Utilities
Emoji 解析器与工具集

功能：
1. 解析文本中的所有 Emoji
2. Emoji 转 Unicode 字符串
3. Unicode 字符串转 Emoji
4. 简单的 Emoji 搜索
5. Emoji 含义查询
6. 统计文本中的 Emoji 数量

作者: MarsAssistant
日期: 2026-02-02
"""

import re
import json
from typing import List, Dict, Tuple, Optional


# 常用 Emoji 字典 (简化版)
EMOJI_DICT = {
    "😀": {"name": "Grinning Face", "meaning": "开心的笑脸"},
    "😃": {"name": "Grinning Face with Big Eyes", "meaning": "大笑脸"},
    "😄": {"name": "Grinning Face with Smiling Eyes", "meaning": "微笑眼笑脸"},
    "😁": {"name": "Grinning Face with Smiling Eyes", "meaning": "开心地笑"},
    "😆": {"name": "Laughing Face", "meaning": " laughing face"},
    "😅": {"name": "Sweat Smile", "meaning": "苦笑"},
    "🤣": {"name": "Rolling on the Floor Laughing", "meaning": "笑到打滚"},
    "😂": {"name": "Face with Tears of Joy", "meaning": "笑到流泪"},
    "🙂": {"name": "Slightly Smiling Face", "meaning": "微笑"},
    "🙃": {"name": "Upside-Down Face", "meaning": "倒脸"},
    "😉": {"name": "Winking Face", "meaning": "眨眼"},
    "😊": {"name": "Smiling Face with Smiling Eyes", "meaning": "眯眼笑"},
    "😇": {"name": "Smiling Face with Halo", "meaning": "天使笑"},
    "🥰": {"name": "Smiling Face with Hearts", "meaning": "爱心笑"},
    "😍": {"name": "Smiling Face with Heart-Eyes", "meaning": "爱心眼"},
    "🤩": {"name": "Star-Struck", "meaning": "星星眼"},
    "😘": {"name": "Face Blowing a Kiss", "meaning": "飞吻"},
    "😗": {"name": "Kissing Face", "meaning": "亲亲"},
    "😋": {"name": "Yummy Face", "meaning": "好吃"},
    "😛": {"name": "Zany Face", "meaning": "调皮"},
    "😜": {"name": "Winking Face with Tongue", "meaning": "吐舌眨眼"},
    "🤪": {"name": "Zany Face", "meaning": "疯狂"},
    "😝": {"name": "Tongue Face", "meaning": "吐舌"},
    "🤑": {"name": "Money-Mouth Face", "meaning": "财迷"},
    "🤗": {"name": "Hugging Face", "meaning": "拥抱"},
    "🤭": {"name": "Face with Hand Over Mouth", "meaning": "捂嘴笑"},
    "🤫": {"name": "Shushing Face", "meaning": "嘘"},
    "🤔": {"name": "Thinking Face", "meaning": "思考"},
    "🤐": {"name": "Zipper-Mouth Face", "meaning": "闭嘴"},
    "🤨": {"name": "Raised Eyebrow", "meaning": "挑眉"},
    "😐": {"name": "Neutral Face", "meaning": "面无表情"},
    "😑": {"name": "Expressionless Face", "meaning": "无感"},
    "😶": {"name": "Face Without Mouth", "meaning": "无嘴脸"},
    "😏": {"name": "Smirking Face", "meaning": "得意"},
    "😒": {"name": "Unamused Face", "meaning": "无趣"},
    "🙄": {"name": "Eye Roll", "meaning": "翻白眼"},
    "😬": {"name": "Grimacing Face", "meaning": "龇牙"},
    "🤥": {"name": "Lying Face", "meaning": "说谎"},
    "😌": {"name": "Relieved Face", "meaning": "安心"},
    "😔": {"name": "Pensive Face", "meaning": "沉思"},
    "😪": {"name": "Sleepy Face", "meaning": "困了"},
    "🤤": {"name": "Drooling Face", "meaning": "流口水"},
    "😴": {"name": "Sleeping Face", "meaning": "睡觉"},
    "😷": {"name": "Face with Medical Mask", "meaning": "戴口罩"},
    "🤒": {"name": "Face with Thermometer", "meaning": "发烧"},
    "🤕": {"name": "Face with Bandage", "meaning": "受伤"},
    "🤢": {"name": "Nauseated Face", "meaning": "恶心"},
    "🤮": {"name": "Vomiting Face", "meaning": "呕吐"},
    "🤧": {"name": "Sneezing Face", "meaning": "打喷嚏"},
    "🥵": {"name": "Hot Face", "meaning": "热"},
    "🥶": {"name": "Cold Face", "meaning": "冷"},
    "🥴": {"name": "Woozy Face", "meaning": "晕"},
    "😵": {"name": "Dizzy Face", "meaning": "晕眩"},
    "🤯": {"name": "Exploding Head", "meaning": "震惊"},
    "🤠": {"name": "Cowboy Hat Face", "meaning": "牛仔"},
    "🥳": {"name": "Partying Face", "meaning": "派对"},
    "😎": {"name": "Smiling Face with Sunglasses", "meaning": "酷"},
    "🤓": {"name": "Nerd Face", "meaning": "书呆子"},
    "😕": {"name": "Confused Face", "meaning": "困惑"},
    "😟": {"name": "Worried Face", "meaning": "担心"},
    "🙁": {"name": "Slightly Frowning Face", "meaning": "皱眉"},
    "☹": {"name": "Frowning Face", "meaning": "不开心"},
    "😮": {"name": "Face with Open Mouth", "meaning": "惊讶"},
    "😯": {"name": "Hushed Face", "meaning": "安静"},
    "😲": {"name": "Astonished Face", "meaning": "震惊"},
    "😳": {"name": "Flushed Face", "meaning": "脸红"},
    "🥺": {"name": "Pleading Face", "meaning": "恳求"},
    "😦": {"name": "Frowning Face with Open Mouth", "meaning": "张嘴皱眉"},
    "😧": {"name": "Anguished Face", "meaning": "痛苦"},
    "😨": {"name": "Fearful Face", "meaning": "害怕"},
    "😰": {"name": "Anxious Face with Sweat", "meaning": "焦虑"},
    "😥": {"name": "Sad but Relieved Face", "meaning": "失望但释然"},
    "😢": {"name": "Crying Face", "meaning": "哭泣"},
    "😭": {"name": "Loudly Crying Face", "meaning": "大哭"},
    "😱": {"name": "Face Screaming in Fear", "meaning": "尖叫"},
    "😖": {"name": "Confounded Face", "meaning": "困惑"},
    "😣": {"name": "Persevering Face", "meaning": "坚持"},
    "😞": {"name": "Disappointed Face", "meaning": "失望"},
    "😓": {"name": "Cold Sweat", "meaning": "冷汗"},
    "😩": {"name": "Weary Face", "meaning": "疲惫"},
    "😫": {"name": "Tired Face", "meaning": "累"},
    "🥱": {"name": "Yawning Face", "meaning": "打哈欠"},
    "😤": {"name": "Face with Steam From Nose", "meaning": "哼"},
    "😡": {"name": "Pouting Face", "meaning": "生气"},
    "😠": {"name": "Angry Face", "meaning": "愤怒"},
    "🤬": {"name": "Face with Symbols Over Mouth", "meaning": "咒骂"},
    "😈": {"name": "Smiling Face with Horns", "meaning": "恶魔"},
    "👿": {"name": "Angry Face with Horns", "meaning": "小恶魔"},
    "💀": {"name": "Skull", "meaning": "骷髅"},
    "☠": {"name": "Skull and Crossbones", "meaning": "危险"},
    "💩": {"name": "Pile of Poo", "meaning": "屎"},
    "🤡": {"name": "Clown Face", "meaning": "小丑"},
    "👻": {"name": "Ghost", "meaning": "鬼"},
    "👽": {"name": "Alien", "meaning": "外星人"},
    "👾": {"name": "Alien Monster", "meaning": "外星怪物"},
    "🤖": {"name": "Robot", "meaning": "机器人"},
    "💋": {"name": "Kiss Mark", "meaning": "唇印"},
    "👋": {"name": "Waving Hand", "meaning": "挥手"},
    "🤚": {"name": "Raised Hand", "meaning": "举手"},
    "🖐": {"name": "Hand with Fingers Splayed", "meaning": "手掌"},
    "✋": {"name": "Raised Hand", "meaning": "举手"},
    "🖖": {"name": "Vulcan Salute", "meaning": "瓦肯礼"},
    "👌": {"name": "OK Hand", "meaning": "OK"},
    "🤌": {"name": "Pinched Hand", "meaning": "捏手势"},
    "🤏": {"name": "Pinching Hand", "meaning": "捏"},
    "✌": {"name": "Victory Hand", "meaning": "胜利"},
    "🤞": {"name": "Crossed Fingers", "meaning": "祈祷"},
    "🤟": {"name": "Love-You Gesture", "meaning": "我爱你"},
    "🤘": {"name": "Sign of the Horns", "meaning": "摇滚"},
    "🤙": {"name": "Call Me Hand", "meaning": "call me"},
    "👈": {"name": "Backhand Index Pointing Left", "meaning": "左指"},
    "👉": {"name": "Backhand Index Pointing Right", "meaning": "右指"},
    "👆": {"name": "Backhand Index Pointing Up", "meaning": "上指"},
    "🖕": {"name": "Middle Finger", "meaning": "中指"},
    "👇": {"name": "Backhand Index Pointing Down", "meaning": "下指"},
    "👍": {"name": "Thumbs Up", "meaning": "点赞"},
    "👎": {"name": "Thumbs Down", "meaning": "差评"},
    "✊": {"name": "Raised Fist", "meaning": "拳头"},
    "👊": {"name": "Oncoming Fist", "meaning": "出拳"},
    "🤛": {"name": "Left-Facing Fist", "meaning": "左拳"},
    "🤜": {"name": "Right-Facing Fist", "meaning": "右拳"},
    "👏": {"name": "Clapping Hands", "meaning": "鼓掌"},
    "🙌": {"name": "Raising Hands", "meaning": "举手欢呼"},
    "👐": {"name": "Open Hands", "meaning": "张开手"},
    "🤲": {"name": "Palms Up Together", "meaning": "手掌向上"},
    "🤝": {"name": "Handshake", "meaning": "握手"},
    "🙏": {"name": "Folded Hands", "meaning": "双手合十"},
    "✍": {"name": "Writing Hand", "meaning": "写字"},
    "💪": {"name": "Flexed Biceps", "meaning": "肌肉"},
    "👂": {"name": "Ear", "meaning": "耳朵"},
    "🦻": {"name": "Ear with Hearing Aid", "meaning": "助听器"},
    "👃": {"name": "Nose", "meaning": "鼻子"},
    "🧠": {"name": "Brain", "meaning": "大脑"},
    "🦷": {"name": "Tooth", "meaning": "牙齿"},
    "🦴": {"name": "Bone", "meaning": "骨头"},
    "👀": {"name": "Eyes", "meaning": "眼睛"},
    "👁": {"name": "Eye", "meaning": "单眼"},
    "👅": {"name": "Tongue", "meaning": "舌头"},
    "👄": {"name": "Mouth", "meaning": "嘴巴"},
    "💄": {"name": "Lipstick", "meaning": "口红"},
    "💅": {"name": "Nail Polish", "meaning": "指甲油"},
    "🤳": {"name": "Selfie", "meaning": "自拍"},
    "👑": {"name": "Crown", "meaning": "皇冠"},
    "🎩": {"name": "Top Hat", "meaning": "礼帽"},
    "👒": {"name": "Hat", "meaning": "帽子"},
    "🎓": {"name": "Graduation Cap", "meaning": "毕业帽"},
    "⛑": {"name": "Rescue Helmet", "meaning": "安全帽"},
    "💍": {"name": "Ring", "meaning": "戒指"},
    "💎": {"name": "Gem Stone", "meaning": "宝石"},
    "💼": {"name": "Briefcase", "meaning": "公文包"},
    "🎒": {"name": "Backpack", "meaning": "背包"},
    "👜": {"name": "Handbag", "meaning": "手提包"},
    "👝": {"name": "Purse", "meaning": "钱包"},
    "👛": {"name": "Purse", "meaning": "钱包"},
    "🛍": {"name": "Shopping Bags", "meaning": "购物袋"},
    "🎈": {"name": "Balloon", "meaning": "气球"},
    "🎉": {"name": "Party Popper", "meaning": "庆祝"},
    "🎊": {"name": "Confetti Ball", "meaning": "五彩纸屑"},
    "🎋": {"name": "Tanabata Tree", "meaning": "七夕树"},
    "🎍": {"name": "Pine Decoration", "meaning": "门松"},
    "🎎": {"name": "Dolls", "meaning": "人偶"},
    "🎏": {"name": "Carp Streamer", "meaning": "鲤鱼旗"},
    "🎐": {"name": "Wind Chime", "meaning": "风铃"},
    "🧧": {"name": "Red Envelope", "meaning": "红包"},
    "🎀": {"name": "Ribbon", "meaning": "蝴蝶结"},
    "🎁": {"name": "Wrapped Gift", "meaning": "礼物"},
    "🎫": {"name": "Ticket", "meaning": "票"},
    "🎖": {"name": "Military Medal", "meaning": "勋章"},
    "🏆": {"name": "Trophy", "meaning": "奖杯"},
    "🏅": {"name": "Sports Medal", "meaning": "奖牌"},
    "🥇": {"name": "Gold Medal", "meaning": "金牌"},
    "🥈": {"name": "Silver Medal", "meaning": "银牌"},
    "🥉": {"name": "Bronze Medal", "meaning": "铜牌"},
    "⚽": {"name": "Soccer Ball", "meaning": "足球"},
    "⚾": {"name": "Baseball", "meaning": "棒球"},
    "🏀": {"name": "Basketball", "meaning": "篮球"},
    "🏐": {"name": "Volleyball", "meaning": "排球"},
    "🏈": {"name": "American Football", "meaning": "美式足球"},
    "🏉": {"name": "Rugby Football", "meaning": "橄榄球"},
    "🎾": {"name": "Tennis", "meaning": "网球"},
    "🏸": {"name": "Badminton", "meaning": "羽毛球"},
    "🥊": {"name": "Boxing Glove", "meaning": "拳击手套"},
    "🥋": {"name": "Martial Arts Uniform", "meaning": "柔道服"},
    "🥅": {"name": "Goal Net", "meaning": "球门"},
    "⛳": {"name": "Flag in Hole", "meaning": "高尔夫"},
    "⛸": {"name": "Ice Skate", "meaning": "滑冰"},
    "🎣": {"name": "Fishing Pole", "meaning": "钓鱼"},
    "🎽": {"name": "Running Shirt", "meaning": "跑步衫"},
    "🎿": {"name": "Skis", "meaning": "滑雪板"},
    "🛷": {"name": "Sled", "meaning": "雪橇"},
    "🥌": {"name": "Curling Stone", "meaning": "冰壶"},
    "🧗": {"name": "Climbing", "meaning": "攀岩"},
    "🏄": {"name": "Surfing", "meaning": "冲浪"},
    "🏊": {"name": "Swimming", "meaning": "游泳"},
    "🚣": {"name": "Rowboat", "meaning": "划船"},
    "🧘": {"name": "Yoga", "meaning": "瑜伽"},
    "🏋️": {"name": "Weight Lifting", "meaning": "举重"},
    "🚴": {"name": "Biking", "meaning": "骑车"},
    "🚵": {"name": "Mountain Biking", "meaning": "山地车"},
    "🏎️": {"name": "Racing Car", "meaning": "赛车"},
    "🚲": {"name": "Bicycle", "meaning": "自行车"},
    "🛴": {"name": "Scooter", "meaning": "滑板车"},
    "🚂": {"name": "Locomotive", "meaning": "火车头"},
    "🚃": {"name": "Railway Car", "meaning": "火车"},
    "🚄": {"name": "High-Speed Train", "meaning": "高铁"},
    "🚅": {"name": "Bullet Train", "meaning": "子弹头"},
    "🚆": {"name": "Train", "meaning": "火车"},
    "🚇": {"name": "Metro", "meaning": "地铁"},
    "🚈": {"name": "Light Rail", "meaning": "轻轨"},
    "🚉": {"name": "Station", "meaning": "车站"},
    "🚌": {"name": "Bus", "meaning": "公交车"},
    "🚍": {"name": "Oncoming Bus", "meaning": "迎面公交车"},
    "🚎": {"name": "Trolleybus", "meaning": "无轨电车"},
    "🚐": {"name": "Minibus", "meaning": "小巴"},
    "🚑": {"name": "Ambulance", "meaning": "救护车"},
    "🚒": {"name": "Fire Engine", "meaning": "消防车"},
    "🚓": {"name": "Police Car", "meaning": "警车"},
    "🚔": {"name": "Oncoming Police Car", "meaning": "警车"},
    "🚕": {"name": "Taxi", "meaning": "出租车"},
    "🚖": {"name": "Oncoming Taxi", "meaning": "出租车"},
    "🚗": {"name": "Car", "meaning": "汽车"},
    "🚙": {"name": "SUV", "meaning": "越野车"},
    "🚚": {"name": "Truck", "meaning": "卡车"},
    "🚛": {"name": "Articulated Lorry", "meaning": "牵引车"},
    "🚜": {"name": "Tractor", "meaning": "拖拉机"},
    "🏍️": {"name": "Motorcycle", "meaning": "摩托车"},
    "🛵": {"name": "Motor Scooter", "meaning": "电动车"},
    "🚏": {"name": "Bus Stop", "meaning": "公交站"},
    "⛽": {"name": "Fuel Pump", "meaning": "加油站"},
    "🚨": {"name": "Police Cars Light", "meaning": "警灯"},
    "🚥": {"name": "Horizontal Traffic Light", "meaning": "红绿灯"},
    "🚦": {"name": "Vertical Traffic Light", "meaning": "红绿灯"},
    "🛑": {"name": "Stop Sign", "meaning": "停止标志"},
    "🌍": {"name": "Earth Globe Europe-Africa", "meaning": "地球"},
    "🌎": {"name": "Earth Globe Americas", "meaning": "地球"},
    "🌏": {"name": "Earth Globe Asia-Australia", "meaning": "地球"},
    "🌐": {"name": "Globe with Meridians", "meaning": "地球仪"},
    "🗺️": {"name": "World Map", "meaning": "世界地图"},
    "🧭": {"name": "Compass", "meaning": "指南针"},
    "🏔️": {"name": "Snow-Capped Mountain", "meaning": "雪山"},
    "⛰️": {"name": "Mountain", "meaning": "山"},
    "🌋": {"name": "Volcano", "meaning": "火山"},
    "🗻": {"name": "Mount Fuji", "meaning": "富士山"},
    "🏕️": {"name": "Camping", "meaning": "露营"},
    "🏖️": {"name": "Beach", "meaning": "海滩"},
    "🏜️": {"name": "Desert", "meaning": "沙漠"},
    "🏝️": {"name": "Desert Island", "meaning": "岛屿"},
    "🏞️": {"name": "National Park", "meaning": "国家公园"},
    "🏟️": {"name": "Stadium", "meaning": "体育场"},
    "🏛️": {"name": "Classical Building", "meaning": "古典建筑"},
    "🏗️": {"name": "Building Construction", "meaning": "建筑中"},
    "🏚️": {"name": "Derelict House", "meaning": "废墟"},
    "🏠": {"name": "House", "meaning": "房子"},
    "🏡": {"name": "House with Garden", "meaning": "带花园的房子"},
    "🏢": {"name": "Office Building", "meaning": "办公楼"},
    "🏣": {"name": "Japanese Post Office", "meaning": "邮局"},
    "🏤": {"name": "Post Office", "meaning": "邮局"},
    "🏥": {"name": "Hospital", "meaning": "医院"},
    "🏦": {"name": "Bank", "meaning": "银行"},
    "🏨": {"name": "Hotel", "meaning": "酒店"},
    "🏩": {"name": "Love Hotel", "meaning": "情人酒店"},
    "🏪": {"name": "Convenience Store", "meaning": "便利店"},
    "🏫": {"name": "School", "meaning": "学校"},
    "🏬": {"name": "Department Store", "meaning": "百货商店"},
    "🏭": {"name": "Factory", "meaning": "工厂"},
    "🏯": {"name": "Japanese Castle", "meaning": "城堡"},
    "🏰": {"name": "Castle", "meaning": "城堡"},
    "💒": {"name": "Wedding", "meaning": "婚礼"},
    "🗼": {"name": "Tokyo Tower", "meaning": "塔"},
    "🗽": {"name": "Statue of Liberty", "meaning": "自由女神"},
    "💊": {"name": "Pill", "meaning": "药丸"},
    "💉": {"name": "Syringe", "meaning": "注射器"},
    "🩸": {"name": "Drop of Blood", "meaning": "血液"},
    "🩹": {"name": "Adhesive Bandage", "meaning": "创可贴"},
    "🩺": {"name": "Stethoscope", "meaning": "听诊器"},
    "🌡️": {"name": "Thermometer", "meaning": "温度计"},
    "💧": {"name": "Drop", "meaning": "水滴"},
    "💦": {"name": "Sweat Droplets", "meaning": "汗滴"},
    "☔": {"name": "Umbrella with Rain", "meaning": "雨伞"},
    "⚡": {"name": "High Voltage", "meaning": "闪电"},
    "🔥": {"name": "Fire", "meaning": "火"},
    "✨": {"name": "Sparkles", "meaning": "闪光"},
    "🌈": {"name": "Rainbow", "meaning": "彩虹"},
    "💫": {"name": "Dizzy", "meaning": "眩晕"},
    "⭐": {"name": "Star", "meaning": "星星"},
    "🌟": {"name": "Glowing Star", "meaning": "闪星"},
    "💥": {"name": "Collision", "meaning": "碰撞"},
    "💢": {"name": "Anger Symbol", "meaning": "怒气"},
    "💬": {"name": "Speech Balloon", "meaning": "对话框"},
    "💭": {"name": "Thought Balloon", "meaning": "思考气泡"},
    "💤": {"name": "Zzz", "meaning": "睡觉"},
    "💨": {"name": "Dash", "meaning": "跑步"},
    "💣": {"name": "Bomb", "meaning": "炸弹"},
    "🚀": {"name": "Rocket", "meaning": "火箭"},
    "🚁": {"name": "Helicopter", "meaning": "直升机"},
    "🚟": {"name": "Suspension Railway", "meaning": "悬挂铁路"},
    "🚠": {"name": "Mountain Cableway", "meaning": "缆车"},
    "🚡": {"name": "Aerial Tramway", "meaning": "空中电车"},
    "🛩️": {"name": "Airplane", "meaning": "飞机"},
    "🛫": {"name": "Airplane Departure", "meaning": "起飞"},
    "🛬": {"name": "Airplane Arrival", "meaning": "降落"},
    "🛫": {"name": "Airplane Departure", "meaning": "飞机起飞"},
    "🛬": {"name": "Airplane Arrival", "meaning": "飞机降落"},
    "💺": {"name": "Seat", "meaning": "座位"},
    "🚪": {"name": "Door", "meaning": "门"},
    "🪑": {"name": "Chair", "meaning": "椅子"},
    "🚽": {"name": "Toilet", "meaning": "厕所"},
    "🚿": {"name": "Shower", "meaning": "淋浴"},
    "🛁": {"name": "Bathtub", "meaning": "浴缸"},
    "🛀": {"name": "Person Taking Bath", "meaning": "泡澡"},
    "🧼": {"name": "Soap", "meaning": "肥皂"},
    "🪒": {"name": "Razor", "meaning": "剃须刀"},
    "🧽": {"name": "Sponge", "meaning": "海绵"},
    "🧴": {"name": "Lotion Bottle", "meaning": "乳液"},
    "🛎️": {"name": "Bellhop Bell", "meaning": "门铃"},
    "🔑": {"name": "Key", "meaning": "钥匙"},
    "🗝️": {"name": "Old Key", "meaning": "旧钥匙"},
    "🚪": {"name": "Door", "meaning": "门"},
    "🪑": {"name": "Chair", "meaning": "椅子"},
    "🛋️": {"name": "Couch and Lamp", "meaning": "沙发"},
    "🛏️": {"name": "Bed", "meaning": "床"},
    "🛌": {"name": "Person in Bed", "meaning": "躺在床上"},
    "🖼️": {"name": "Framed Picture", "meaning": "画框"},
    "🛍️": {"name": "Shopping Bags", "meaning": "购物袋"},
    "🛒": {"name": "Shopping Cart", "meaning": "购物车"},
    "🎁": {"name": "Wrapped Gift", "meaning": "礼物"},
    "🎈": {"name": "Balloon", "meaning": "气球"},
    "🎉": {"name": "Party Popper", "meaning": "庆祝"},
    "🎊": {"name": "Confetti Ball", "meaning": "五彩纸屑"},
    "🎋": {"name": "Tanabata Tree", "meaning": "七夕树"},
    "🎍": {"name": "Pine Decoration", "meaning": "门松"},
    "🎎": {"name": "Dolls", "meaning": "人偶"},
    "🎏": {"name": "Carp Streamer", "meaning": "鲤鱼旗"},
    "🎐": {"name": "Wind Chime", "meaning": "风铃"},
    "🎑": {"name": "Moon Viewing Ceremony", "meaning": "赏月"},
    "🧧": {"name": "Red Envelope", "meaning": "红包"},
    "🎀": {"name": "Ribbon", "meaning": "蝴蝶结"},
    "🎁": {"name": "Wrapped Gift", "meaning": "礼物"},
    "🎗️": {"name": "Reminder Ribbon", "meaning": "丝带"},
    "🎟️": {"name": "Admission Ticket", "meaning": "入场券"},
    "🎫": {"name": "Ticket", "meaning": "票"},
    "🎙️": {"name": "Studio Microphone", "meaning": "麦克风"},
    "🎚️": {"name": "Level Slider", "meaning": "滑块"},
    "🎛️": {"name": "Control Knobs", "meaning": "控制旋钮"},
    "🎤": {"name": "Microphone", "meaning": "麦克风"},
    "🎧": {"name": "Headphone", "meaning": "耳机"},
    "🎼": {"name": "Musical Score", "meaning": "乐谱"},
    "🎹": {"name": "Musical Keyboard", "meaning": "键盘"},
    "🎸": {"name": "Guitar", "meaning": "吉他"},
    "🎷": {"name": "Saxophone", "meaning": "萨克斯"},
    "🎺": {"name": "Trumpet", "meaning": "小号"},
    "🎻": {"name": "Violin", "meaning": "小提琴"},
    "🥁": {"name": "Drum", "meaning": "鼓"},
    "🎵": {"name": "Musical Note", "meaning": "音符"},
    "🎶": {"name": "Musical Notes", "meaning": "多个音符"},
    "🎙️": {"name": "Studio Microphone", "meaning": "录音室麦克风"},
    "🎚️": {"name": "Level Slider", "meaning": "电平滑块"},
    "🎛️": {"name": "Control Knobs", "meaning": "控制旋钮"},
    "🎫": {"name": "Ticket", "meaning": "票"},
    "🏆": {"name": "Trophy", "meaning": "奖杯"},
    "🏅": {"name": "Sports Medal", "meaning": "奖牌"},
    "🥇": {"name": "Gold Medal", "meaning": "金牌"},
    "🥈": {"name": "Silver Medal", "meaning": "银牌"},
    "🥉": {"name": "Bronze Medal", "meaning": "铜牌"},
    "⚽": {"name": "Soccer Ball", "meaning": "足球"},
    "⚾": {"name": "Baseball", "meaning": "棒球"},
    "🥎": {"name": "Softball", "meaning": "垒球"},
    "🏀": {"name": "Basketball", "meaning": "篮球"},
    "🏐": {"name": "Volleyball", "meaning": "排球"},
    "🏈": {"name": "American Football", "meaning": "美式足球"},
    "🏉": {"name": "Rugby Football", "meaning": "橄榄球"},
    "🎾": {"name": "Tennis", "meaning": "网球"},
    "🥏": {"name": "Flying Disc", "meaning": "飞盘"},
    "🎳": {"name": "Bowling", "meaning": "保龄球"},
    "🏏": {"name": "Cricket Game", "meaning": "板球"},
    "🏑": {"name": "Field Hockey", "meaning": "曲棍球"},
    "🏒": {"name": "Ice Hockey", "meaning": "冰球"},
    "🥍": {"name": "Lacrosse", "meaning": "袋棍球"},
    "🏓": {"name": "Ping Pong", "meaning": "乒乓球"},
    "🏸": {"name": "Badminton", "meaning": "羽毛球"},
    "🥊": {"name": "Boxing Glove", "meaning": "拳击手套"},
    "🥋": {"name": "Martial Arts Uniform", "meaning": "柔道服"},
    "🥅": {"name": "Goal Net", "meaning": "球门"},
    "⛳": {"name": "Flag in Hole", "meaning": "高尔夫"},
    "⛸": {"name": "Ice Skate", "meaning": "滑冰"},
    "🎣": {"name": "Fishing Pole", "meaning": "钓鱼"},
    "🤿": {"name": "Diving Mask", "meaning": "潜水镜"},
    "🎽": {"name": "Running Shirt", "meaning": "跑步衫"},
    "🎿": {"name": "Skis", "meaning": "滑雪板"},
    "🛷": {"name": "Sled", "meaning": "雪橇"},
    "🥌": {"name": "Curling Stone", "meaning": "冰壶"},
    "🧗": {"name": "Climbing", "meaning": "攀岩"},
    "🏄": {"name": "Surfing", "meaning": "冲浪"},
    "🏊": {"name": "Swimming", "meaning": "游泳"},
    "🤽": {"name": "Water Polo", "meaning": "水球"},
    "🚣": {"name": "Rowboat", "meaning": "划船"},
    "🧘": {"name": "Yoga", "meaning": "瑜伽"},
    "🏋️": {"name": "Weight Lifting", "meaning": "举重"},
    "🚴": {"name": "Biking", "meaning": "骑车"},
    "🚵": {"name": "Mountain Biking", "meaning": "山地车"},
    "🏎️": {"name": "Racing Car", "meaning": "赛车"},
    "🚲": {"name": "Bicycle", "meaning": "自行车"},
    "🛴": {"name": "Scooter", "meaning": "滑板车"},
}


class EmojiTools:
    """Emoji 工具类"""
    
    def __init__(self):
        """初始化 Emoji 工具"""
        self.emoji_dict = EMOJI_DICT
    
    def extract_emojis(self, text: str) -> List[str]:
        """从文本中提取所有 Emoji
        
        Args:
            text: 输入文本
            
        Returns:
            包含所有找到的 Emoji 的列表
        """
        # 使用正则表达式匹配 Emoji
        # 匹配 Unicode 范围内的 Emoji
