# Python Decorators Collection
# Day 036: Decorators
# Generated by AI Agent

import functools
import time

def timer(func):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        print(f'{func.__name__}: {time.time()-start:.4f}s')
        return result
    return wrapper

def cache(func):
    cache_dict = {}
    @functools.wraps(func)
    def wrapper(*args):
        if args in cache_dict:
            return cache_dict[args]
        result = func(*args)
        cache_dict[args] = result
        return result
    return wrapper

if __name__ == '__main__':
    @timer
    def slow_function():
        time.sleep(0.1)
        return 'done'
    
    print(slow_function())
