# Data Structures Implementation
# Day 032: Data Structures
# Generated by AI Agent

class Stack:
    def __init__(self):
        self._items = []
    
    def push(self, item):
        self._items.append(item)
    
    def pop(self):
        return self._items.pop() if self._items else None
    
    def peek(self):
        return self._items[-1] if self._items else None
    
    def is_empty(self):
        return len(self._items) == 0

class Queue:
    def __init__(self):
        self._items = []
    
    def enqueue(self, item):
        self._items.append(item)
    
    def dequeue(self):
        return self._items.pop(0) if self._items else None

if __name__ == '__main__':
    s = Stack()
    for i in range(5):
        s.push(i)
    print(f'Stack pop: {s.pop()}')
    print(f'Stack size: {s.size()}')
