# Text Processing Utilities
# Day 033: Text Processing
# Generated by AI Agent

import re

def reverse_text(text):
    return text[::-1]

def word_count(text):
    return len(text.split())

def is_palindrome(text):
    cleaned = re.sub(r'[^a-zA-Z0-9]', '', text.lower())
    return cleaned == cleaned[::-1]

def slugify(text):
    return re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')

if __name__ == '__main__':
    sample = 'A man, a plan, a canal: Panama'
    print(f'Original: {sample}')
    print(f'Is palindrome: {is_palindrome(sample)}')
