# Search Algorithms Collection
# Day 034: Search Algorithms
# Generated by AI Agent

def linear_search(arr, target):
    for i, val in enumerate(arr):
        if val == target:
            return i
    return -1

def binary_search(arr, target):
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1

if __name__ == '__main__':
    data = [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
    print(f'Data: {data}')
    print(f'Binary search for 9: index {binary_search(data, 9)}')
