# Sorting Algorithms Collection
# Day 033: Sorting Algorithms
# Generated by AI Agent

def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quick_sort(left) + middle + quick_sort(right)

if __name__ == '__main__':
    test = [64, 34, 25, 12, 22, 11, 90]
    print(f'Original: {test}')
    print(f'Bubble sort: {bubble_sort(test.copy())}')
    print(f'Quick sort: {quick_sort(test)}')
