# File Utilities Collection
# Day 036: File Utilities
# Generated by AI Agent

from pathlib import Path

def read_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        return f.read()

def write_file(filepath, content):
    Path(filepath).parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

def list_files(directory, extension=None):
    path = Path(directory)
    if extension:
        return [f for f in path.iterdir() if f.is_file() and f.suffix == extension]
    return [f for f in path.iterdir() if f.is_file()]

if __name__ == '__main__':
    print('File utilities loaded')
