#!/usr/bin/env python3

## ACL OF THIS FILE IS GENERATED BY MARS ASSISTANT

# https://github.com/my1162709774/MarsAssistant-Code-Journey

## Day 12: Intelligent Code Comment Generator

!#!/usr/bin/env python3
"""
AI代码助手 - 智能代码注释生成器
Intelligent Code Comment Generator

功能：自动为代码生成清晰、简洁、有意义的注释
"""

import random
from typing import List, Dict

class CodeCommentGenerator:
    """智能代码注释生成器类"""
    
    # 注释风格模板
    COMMENT_STYLAS = {
        "python": {
            "function": [
                "执行{action}操作",
                "处理{description}逻辑",
                "实现核心{action}功能",
                "处理输入并返回{output}结果"
            ],
            "variable": [
                "存储{description}",
                "用于记录{usage}",
                "配置参数: {description}"
            ],
            "class": [
                "定义{description}类",
                "封装{responsibility}逻辑"
            ]
        },
        "javascript": {
            "function": [
                "Executes {action} operation",
                "Handles {description} logic",
                "Implements core {action} functionality"
            ],
            "variable": [
                "Stores {description}",
                "Used for {usage}",
                "Configuration: {description}"
            ]
        }
    }
    
    # 代码类型关键词
    ACTION_VERBS = [
        "数据处理", "文件操作", "网络请求", "算法计算",
        "数据验证", "格式转换", "缓存管理", "日志记录",
        "用户认证", "权限检查", "错误处理", "性能优化"
    ]
    
    def __init__(self, language: str = "python"):
        """初始化注释生成器
        
        Args:
            language: 编程语言 (python/javascript)
        """
        self.language = language
        self.history: List[Dict] = []
    
    def generate_function_comment(self, func_name: str, description: str) -> str:
        """为函数生成注释
        
        Args:
            func_name: 函数名称
            description: 函数描述
            
        Returns:
            生成的注释字符串
        """
        action = self._extract_action(func_name, description)
        style = random.choice(self.COMMENT_STYLES[self.language]["function"])
        comment = style.format(action=action, description=description, output="处理后的")
        
        self.history.append({
            "type": "function",
            "name": func_name,
            "comment": comment
        })
        
        return self._format_comment(comment, "function")
    
    def generate_variable_comment(self, var_name: str, description: str, usage: str = "") -> str:
        """为变量生成注释
        
        Args:
            var_name: 变量名称
            description: 变量描述
            usage: 用途说明
            
        Returns:
            生成的注释字符串
        """
        style = random.choice(self.COMMENT_STYLES[self.language]["variable"])
        comment = style.format(
            description=description,
            usage=usage or f"用于{self._random_action()}"
        )
        
        self.history.append({
            "type": "variable",
            "name": var_name,
            "comment": comment
        })
        
        return self._format_comment(comment, "variable")
    
    def _extract_action(self, name: str, description: str) -> str:
        """从名称和描述中提取动作词"""
        # 常见动作词映射
        action_map = {
            "get": "获取",
            "set": "设置",
            "create": "创建",
            "update": "更新",
            "delete": "删除",
            "process": "处理",
            "validate": "验证",
            "transform": "转换",
            "calculate": "计算",
            "fetch": "抓取",
            "render": "渲染"
        }
        
        name_lower = name.lower()
        for key, action in action_map.items():
            if key in name_lower:
                return action
        
        # 从描述中提取
        for verb in self.ACTION_VERBS:
            if verb in description:
                return verb
        
        return self._random_action()
    
    def _random_action(self) -> str:
        """随机选择一个动作词"""
        return random.choice(self.ACTION_VERBS)
    
    def _format_comment(self, text: str, type: str) -> str:
        """格式化注释"""
        if self.language == "python":
            if type == "function":
                return f'    """{text}"""\n'
            else:
                return f'    # {text}\n'
        else:  # javascript
            return f"    // {text}\n"
    
    def batch_generate(self, code_elements: List[Dict]) -> Dict[str, str]:
        """批量生成注释
        
        Args:
            code_elements: 代码元素列表 [{"name": "xxx", "type": "function", "desc": "..."}]
            
        Returns:
            名称到注释的映射
        """
        result = {}
        for element in code_elements:
            if element["type"] == "function":
                result[element["name"]] = self.generate_function_comment(
                    element["name"], 
                    element.get("desc", "处理逻辑")
                )
            else:
                result[element["name"]] = self.generate_variable_comment(
                    element["name"],
                    element.get("desc", "变量"),
                    element.get("usage", "")
                )
        return result


def demo():
    """演示智能注释生成器"""
    generator = CodeCommentGenerator("python")
    
    # 示例：为一组代码元素生成注释
    code_elements = [
        {"name": "get_user_data", "type": "function", "desc": "获取用户信息"},
        {"name": "validate_email", "type": "function", "desc": "验证邮箱格式"},
        {"name": "cache_manager", "type": "variable", "desc": "缓存管理器实例"},
        {"name": "process_payment", "type": "function", "desc": "处理支付逻辑"}
    ]
    
    comments = generator.batch_generate(code_elements)
    
    print("=== 智能代码注释生成器演示 ===\n")
    
    for name, comment in comments.items():
        print(f"元素: {name}")
        print(f"注释: {comment}")
        print("-" * 40)
    
    print(f"\n总共生成 {len(comments)} 条注释")


if __name__ == "__main__":
    demo()

